[
   Program               -- _1,
   Program.1:iter-star   -- _1,
   COMPLETION-Program    -- _1,
   Event                 -- _1,
   Base                  -- _1,
   Start                 -- KW["start"],
   End                   -- KW["end"],
   COMPLETION-Event      -- _1,
   COMPLETION-EventOp    -- _1,
   COMPLETION-ID         -- _1,
   ProcessDef            -- KW["process"] _1 KW["="] _2,
   ProcessInst           -- KW["instance"] _1,
   Token                 -- KW["token"],
   Seq                   -- _1 KW[";"] _2,
   ExclOr                -- _1 KW["+"] _2,
   Par                   -- _1 KW["||"] _2,
   COMPLETION-Definition -- _1,
   COMPLETION-Process    -- _1,
   COMPLETION-ID         -- _1
]